### ISSUE TITLE
Can use zk/etcd to dynamically change the proxy config

### ISSUE THREAD

**Issue by duffqiu** [networknt/light-proxy#5]
For example, dynamically add a new external interface without reboot the proxy

**Comment by stevehu** [comment]
Yes. It is doable but not high priority at the moment. The light-proxy is primary used to bring legacy restful APIs into our light ecosystem so that they can enjoy the infrastructure services and cross-cutting concerns. Would you mind to let us know your use case? Maybe we can work together to get it implemented. Thanks.
